### ISSUE TITLE
Write installation docs

### ISSUE THREAD

**Issue by julianser** [mila-udem/fuel#104]
Add to Readme.rst that libraries certifi and urllib3 are prerequisites, and add instructions on how to install these @vdumoulin.

**Comment by vdumoulin** [comment]
Normally `setup.py` should handle dependencies for you. What was your installation procedure for Fuel?

**Comment by dwf** [comment]
We should probably have installation docs similar to Blocks so I've changed the title of this ticket.

**Comment by dwf** [comment]
Note: as of the merge of #196, Fuel will include some compiled code (Cython). We should carefully document this. `pip install` should work, but editable mode requires some care if you edit the Cython files (i.e. you need to rebuild in-place). See [this comment](https://github.com/mila-udem/fuel/pull/196#discussion_r34636213).
