### ISSUE TITLE
More robust download function

### ISSUE THREAD

**Issue by dwf** [mila-udem/fuel#117]
Some datasets are hundreds of gigabytes. Currently the default downloader provides no notion of progress, let alone support for resumption.

Surely there's a library out there that we can offload all of this to...

**Comment by vdumoulin** [comment]
[requests](http://docs.python-requests.org/en/latest/)? Would its Apache2 license be problematic?

**Comment by bartvm** [comment]
Apache2 licence is fine to depend on I think since we're not modifying the
code or anything.
