### ISSUE TITLE
API docs aren't building on RTD

### ISSUE THREAD

**Issue by dwf** [mila-udem/fuel#143]

**Comment by bartvm** [comment]
I had a look before, and again just now. Not sure what to do about the PyTables installation crashing, because we can't delete it from `setup.py` I guess. This 26b77cc3f13df8e75601d8564e9ae829e367cc82 should fix some of the errors at least.

**Comment by vdumoulin** [comment]
Hey, is it normal that the repo on ReadTheDocs still points to bartvm/fuel?

**Comment by bartvm** [comment]
I changed the links in the configuration panel, hopefully that's enough. Also, the edits from https://github.com/mila-udem/fuel/commit/26b77cc3f13df8e75601d8564e9ae829e367cc82 seem to have fixed the builds, so everything is okay now I think.
