### ISSUE TITLE
Cross validation support

### ISSUE THREAD

**Issue by dwf** [mila-udem/fuel#146]
We should provide support for splitting a (finite) dataset into K folds and producing K pairs of training sets and validation sets from these folds.

You may want the folds to be stratified such that each class is represented in each fold with roughly the same proportion as in the wider training set. I have some code for this.

**Comment by bartvm** [comment]
This is pretty relevant to this discussion: https://github.com/mila-udem/fuel/issues/101#issuecomment-99866739

**Comment by dwf** [comment]
Mhmm. I think we could at least provide convenient functions to use for generating subsets, if not convenience wrappers that generate various DataStreams.

**Comment by bartvm** [comment]
Yeah, agreed, my point was mostly that I think we shouldn't need to introduce any new abstractions, or change the behaviour of existing classes, to make this work. A helper function that generates a series of iteration schemes and/or data streams should be enough.

**Comment by vdumoulin** [comment]
@ejls This is your assigned ticket for this week.

**Comment by vdumoulin** [comment]
Fixed by #176.
