### ISSUE TITLE
Expand "~" in data path

### ISSUE THREAD

**Issue by sisp** [mila-udem/fuel#168]
Hi,

I've started looking into Blocks and Fuel and noticed a small inconvenience when I tried to run the MNIST example. I had set the data path in `.fuelrc` to `~/.fuel/data`, but the `mnist.hdf5` file could not be found because I didn't provide the absolute path. It's not a big deal, but perhaps it's worthwhile to preprocess the data path with `os.path.expanduser`.

Best,
Sigurd

**Comment by vdumoulin** [comment]
Your suggestion is very welcomed!
