### ISSUE TITLE
Local cache for datasets

### ISSUE THREAD

**Issue by lamblin** [mila-udem/fuel#173]
In order to avoid hammering a network drive when several processes need access to a dataset at the same time, which can be a problem at MILA, it would be really useful to have an automatic way of caching datasets on a local drive.
Pylearn2 has had that functionality for a while [[1](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/datasets/cache.py)], and it proved useful to reduce the load on file servers.
One way this could work would be:
- Use a new environment variable, for instance `FUEL_DATA_CACHE` to specify the path of that cache. If that variable is not set, no cache will be used.
- In `fuel.utils.find_in_data_path`, when the original data file is found, try to:
  - see if it is already in the cache, and check that the version is up to date,
  - if not, try to copy if into the cache,
  - if it works, return the path of the cached version, otherwise, return the original path.
- Maybe add an option to `find_in_data_path` to disable caching, for instance `ignore_data_cache`. This can be used by a particular Dataset class to disable caching for its data.

CC @nouiz who worked on the Pylearn2 version.

**Comment by dwf** [comment]
I would caution against doing this automatically if the file exceeds about
a gigabyte (though this could be configurable). I also think it's important
to double check byte size and file metadata written inside to make sure
that a cached version is up to date.

**Comment by nouiz** [comment]
It would be easy to port this. I suggested this by email today to Vincent:)

The code for the cache is located in only one file with no dependencies on
pylearn2. So just copy this file and use it.

As you recently added find_in_data_path, the change will be trivial to use
it.

Copy the file is : pylearn2/datasets/cache.py

the to use it:

from pylearn2.datasets.cache import datasetCache
label_path = datasetCache.cache_file(label_path)

If we can't copy it locally (like no space) we will return the original
path. If we cached it, we will return the local path.

We should take care as if multiple path are in FUEL_DATA_PATH and they have
name that colide, we  could colide them in the local cache. I'm not sure of
that, maybe not, so just double check that behavior.

**Comment by nouiz** [comment]
It was done for the size and metadata check from memory.

We check the size availability and make sure only 1 process do the copy via
a lock (from memory same lock as Theano compiledir).

**Comment by lamblin** [comment]
The code in Pylearn2 currently has a dependency on Theano, though (it re-uses theano's compile lock), but Fuel does not depend on Theano.

**Comment by nouiz** [comment]
I think that part of Theano is standalone, you could copy it too...

**Comment by dwf** [comment]
Let's not worry about name collisions for the first version. I assume the
current behaviour is "first found" (trying to look at that PR, but on my
phone sitting on a delayed airplane...). If there's a mismatch between
cached version and the first found, for now we can just give up.

**Comment by lamblin** [comment]
@dwf I think that is the right behaviour anyway. First found is what we would use if there was no cache, so that is what we should use in all cases.

**Comment by dmitriy-serdyuk** [comment]
@alexmlamb, this is your ticket
