### ISSUE TITLE
fuel-convert tags the wrong file if the converter changes the default file name

### ISSUE THREAD

**Issue by janchorowski** [mila-udem/fuel#175]
`fuel-convert` automatically tags hdf5 files with version information (https://github.com/mila-udem/fuel/blob/master/bin/fuel-convert#L47). By default it tags the file in `args.output_file`. However, certain converters choose to create a differently named file. For instance the SVHN converter will fill the template in `args.output_file` with version information. Then `fuel-convert` creates a new file (`svhn_format_{}.hdf5` in the case of svhn) and tags it, instead of the dataset file.

Probably, the tagging should be factored out and applied from the converter itself. Another solution is to pass the `args` object to converters, instead of unpacking it as dicts. Then the converter can change the argument.

**Comment by vdumoulin** [comment]
You're absolutely right that this behaviour is undesireable. There's a fix for that in #158.

**Comment by vdumoulin** [comment]
Fixed by #158.
