### ISSUE TITLE
ImageNet dataset

### ISSUE THREAD

**Issue by nouiz** [mila-udem/fuel#178]
This have been started here, but it don't have tests and need a rebase/fix for the interface change.

This is a stub ticket, mostly to have it there that we work on it inside fuel.

**Comment by dwf** [comment]
I've largely changed my mind about how this should be handled, by the way.
We should just store the raw JPEG data in HDF5 variable length uint8
arrays. This saves disk and also will be faster to read off of disk.

It means we will need Transformers that do the preprocessing on the fly,
and for it to be fast we will have to rely on the client-server model,
which currently does not support job resumption with Blocks (though we have
a plan for how to do that).

**Comment by nouiz** [comment]
What about making and merging a first working version first?
Le 23 juin 2015 14:24, "David Warde-Farley" <notifications@github.com> a
écrit :

**Comment by dwf** [comment]
The version I've proposed will be an awful lot shorter. I will try and get
to it this week.

**Comment by rodrigob** [comment]
any update on this front ?

**Comment by dwf** [comment]
It's actually high on my list of priorities this week.  Doing it a bit
differently.

**Comment by rodrigob** [comment]
any update on this front ?

(also, what does CCW stands for ?)

**Comment by vdumoulin** [comment]
We have some tests left to write before @dwf 's PR is ready to be merged, but it's still a high priority.

CCW stands for Common Code Workflow, which is the name of the organization at MILA responsible for coordinating the development of common tools, such as Theano, Pylearn2, Blocks and Fuel.

**Comment by rodrigob** [comment]
Ahhh I had not see the PR https://github.com/mila-udem/fuel/pull/68 looking forward to play with it !

**Comment by rodrigob** [comment]
Seems that Pr #68 is in good shape.

What are the plans for ILSVRC2012 and ILSVRC2014 ?
The ILSVRC 2015 challenge used these two for classification and detection respectively.

Sure the test set is not available, but having the training and validation data inside Fuel seems  a reasonable idea.

**Comment by dwf** [comment]
Most of the code I wrote for ILSVRC2010 conversion should be pretty easy to take and apply to other years. H5PYDataset does support sources that have differing folds available, IIRC, so it's possible to stuff the test set images in without labels.
