### ISSUE TITLE
Metainformation in H5PYDataset-compatible files

### ISSUE THREAD

**Issue by rizar** [mila-udem/fuel#180]
A question: have we already decided on a standard way to store such things like e.g. number of classes in hdf5 files? That is, suppose I want to run a training script that train a model on both MNIST and CIFAR, can such a script extract the information about the number of classes in these datasets from hdf5 files?

**Comment by vdumoulin** [comment]
Not at the moment, if I recall correctly. I think the most natural place to put that information would be alongside axis labels. I'll try to find a straightforward way to add meta-information like that in the `dims`.

**Comment by vdumoulin** [comment]
I guess we could use dimension scales to store that information. I don't know of a good interface to retrieve that automatically. Maybe every dimension scale that isn't named `shapes` or `shapes_labels` could be considered meta-information?

**Comment by rizar** [comment]
At this point I should get acquainted a bit more with dimension scales in HDF5. I will get back to this issue soon.

**Comment by rizar** [comment]
By the way, should we also store dimensions this way?

**Comment by vdumoulin** [comment]
@rizar is this issue still relevant?

**Comment by rizar** [comment]
I don't really remember what was the reason to create this issue, which
probably means should close, and open a new one when needed.

**Comment by vdumoulin** [comment]
Alright, thanks!
