### ISSUE TITLE
Cannot iterate over a dataset opened with several subsets.

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [mila-udem/fuel#181]
When I open an HDF5 dataset with a list of subset with more than one element, I cannot iterate over it. Seems, that the issue is only with out-of-memory datasets.

Code to reproduce the issue:
```
In [44]: mnist = H5PYDataset('.../mnist.hdf5', ('train', 'test'))

In [45]: stream = DataStream(mnist, iteration_scheme=SequentialScheme(mnist.num_examples, 100))

In [46]: [data for data in stream.get_epoch_iterator()]
```

**Comment by vdumoulin** [comment]
It has to do with the fact that subset indices are specified as a list which doesn't support fancy indexing. I'll make a PR to fix this very soon.

**Comment by dwf** [comment]
I had a fix for this in IndexableDataset, hopefully we can just reuse that
code and put it in one place.

**Comment by vdumoulin** [comment]
@dwf cool, I did not know that. I opened a PR in #184.
