### ISSUE TITLE
Is IndexableDataset.__getattr__ interfering with pickling?

### ISSUE THREAD

**Issue by vdumoulin** [mila-udem/fuel#183]
Here's a small example exhibiting the issue:

``` python
>>> import pickle
>>> from fuel.datasets import IndexableDataset
>>> dataset = IndexableDataset({'features': [[0, 0], [1, 1]]})
>>> dataset = pickle.loads(pickle.dumps(dataset))
TypeError: argument of type 'NoneType' is not iterable
```

Removing the `__getattr__` method solves the issue, but I'm not familiar enough with pickling to determine whether this is a coincidence or not.

**Comment by rizar** [comment]
The issue is  that `IndexableDataset` doesn't set its `sources` attributes in its constructor.

**Comment by vdumoulin** [comment]
But it sets `self.provides_sources` in its constructor and calls its parent constructor, isn't it equivalent?

**Comment by rizar** [comment]
Maybe it should, but in the debugger it did not have `self.sources` when `__getattr__` was called. If will try to debug why it didn't have them.

**Comment by vdumoulin** [comment]
Weird, in the debugger `dir(self)` contains `'sources'`!

**Comment by rizar** [comment]
Sorry, you are right, it does, but they are `None`.

**Comment by vdumoulin** [comment]
I think I found the issue: the pickler calls `getattr(inst, '__setstate__', None)`, which calls `IndexableDataset`'s `__getattr__` method *before* `self.sources` has been set, which makes it fail.

**Comment by vdumoulin** [comment]
The problem is solved if I add a trivial `__setstate__` method like so:

``` python
def __setstate__(self, dict):
    self.__dict__ = dict
```

**Comment by rizar** [comment]
To be honest I don't understand why `self.sources` is `None`. Shouldn't it default to `provides_sources`?

**Comment by vdumoulin** [comment]
I think it's because unpickling crashed before the unpickled object's attributes were populated.

**Comment by rizar** [comment]
Oh, now I got it!  Then I think your fix is legitimate.
