### ISSUE TITLE
Allow fuel-download and fuel-convert to look for locally-defined downloaders and converters

### ISSUE THREAD

**Issue by vdumoulin** [mila-udem/fuel#190]
This would allow people to re-use those scripts without monkeypatching Fuel to add their own local built-in datasets.

We could define a config variable in the fuelrc file (defaulting to `fuel.[downloaders/converters]`) that would tell in which modules to look for `all_[downloaders/converters]`.

**Comment by dwf** [comment]
Could also pass this as a flag and do the import dynamically. But a fuelrc
setting is nice too.

**Comment by vdumoulin** [comment]
Right. Basically, the same type of behaviour as `FUEL_DATA_PATH`.

**Comment by vdumoulin** [comment]
Closed via #214.
