### ISSUE TITLE
Merge streams never terminate?

### ISSUE THREAD

**Issue by dwf** [mila-udem/fuel#202]
Discovered while trying to pin down #201:

Tested on a branch that is rebased on top of 74634c910... Probably still the case in master:

```python
from fuel.datasets import IterableDataset
from fuel.streams import DataStream
from fuel.transformers import Merge
from fuel.schemes import SequentialScheme
english = IterableDataset(['Hello world!'])
french = IterableDataset(['Bonjour le monde!'])
next(merged_stream.get_epoch_iterator())
streams = (DataStream(english, iteration_scheme=SequentialScheme(batch_size=1, examples=1)),
           DataStream(french, iteration_scheme=SequentialScheme(batch_size=1, examples=1)))
merged_stream = Merge(streams, ('english', 'french'))
iterator = merged_stream.get_epoch_iterator()
next(iterator)
next(iterator)
```
This should raise a `StopIteration` but doesn't. In fact, you get an empty tuple, and keep getting empty tuples seemingly forever.

Returning the same number of items in a tuple than the number of sources for a stream is something that should be `assert`ed.

**Comment by vdumoulin** [comment]
Fixed via #229.
