### ISSUE TITLE
How to run fuel-download on Windows?

### ISSUE THREAD

**Issue by Lyapu** [mila-udem/fuel#204]
I'm trying to run "fuel-download mnist" using Cygwin. I set my environment path variable FUEL_DATA_PATH to C:\Users\Me\Documents\fuel_data. When I run "fuel-download mnist", the error I get is

Me@Me-PC /c/Users/Me/Documents/fuel_data
$ /cygdrive/c/Users/Me/Anaconda/Scripts/fuel-download mnist
C:\Users\Me\Anaconda\python.exe: can't open file '/cygdrive/c/Users/Me/Anaconda/Scripts/fuel-download': [Errno 2] No such file or directory

Am I missing something obvious? Is there an easier way to do this on Windows?

**Comment by dwf** [comment]
Sounds like a Cygwin/Python problem. Anaconda's Python is probably expecting Windows-native paths and doesn't know what the heck to do with a /cygdrive path.

(And Windows is, in general, barely supported, I would say. None of the developers use it, there's no buildbot for it. Patches are welcome but it's a fringe concern from my point of view.)
