### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by rick168** [mila-udem/fuel#207]
http://fuel.readthedocs.org/en/latest/
OS: windows 7
fuel is installed.

>>>from fuel.datasets import MNIST

error: 
  File "C:\Anaconda\lib\site-packages\fuel-0.0.1-py2.7-win-amd64.egg\fuel\config_parser.py", line 82, in load_yaml
    for key, value in yaml.safe_load(f).items():
 AttributeError: 'str' object has no attribute 'items'

How to fix?

In addition, .fuelrc is created under c:\Users\xxx, correct?

FUEL_DATA_PATH="c:\Fueldata", correct?

Thanks!

**Comment by lamblin** [comment]
I should have answered this here, rather than on blocks-users:

> What is the content of your .fuelrc?
> There are two ways of setting the fuel data path:
> - either using the .fuelrc file, in which case is content should be:
> data_path: "c:\Fueldata"
> - or by setting an environment variable named FUEL_DATA_PATH. On Windows, you can do that by typing, in a terminal:
> set FUEL_DATA_PATH="c:\Fueldata"

**Comment by rick168** [comment]
Thank you very much! 
I am using the .fuelrc file. It works well now.
data_path: c:\Fueldata

**Comment by DanlanChen** [comment]
I have the same issue, and I did export the fuel_data_path to the .bashrc file:export FUEL_DATA_PATH="/NOBACKUP/fuel_data_cdl", I do not know why

**Comment by DanlanChen** [comment]
I am on linux

**Comment by bartvm** [comment]
If you get the error at the same line (`for key, value in yaml.safe_load(f).items():)` then the problem is in your YAML file. You'll have to delete or fix your YAML file, setting the environment alone won't fix it.

**Comment by zxinnnn** [comment]
@bartvm  I have the same error and I have set my data_path in ~/.fuelrc. So, is there some problems in my yaml file? and do you know how to fix it? I use the linux system.

**Comment by DanyEle** [comment]
I bumped into the same issue today. Fixed it by uninstalling and erasing the numpy package and re-installing it. For me, this was the solution:

```
pip uninstall numpy
cd /home/daniele/.local/lib/python2.7/site-packages/numpy/
[Or wherever you installed numpy]
sudo rm .r -rf *
pip install numpy

```
