### ISSUE TITLE
Make Fuel accept a list of paths as its data path in fuelrc

### ISSUE THREAD

**Issue by vdumoulin** [mila-udem/fuel#218]
See [this comment](https://github.com/mila-udem/fuel/pull/214#discussion_r37345322).

**Comment by vdumoulin** [comment]
Remember to change the corresponding documentation in Blocks as well.

**Comment by vdumoulin** [comment]
@hantek This is your CCW ticket this week.

**Comment by hantek** [comment]
OK, get it.

On Mon, Aug 31, 2015 at 2:28 PM, vdumoulin <notifications@github.com> wrote:

> @hantek <https://github.com/hantek> This is your CCW ticket this week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mila-udem/fuel/issues/218#issuecomment-136454551>.
>



-- 
LIN, Zhouhan
Department of Computer Science and Operational Research
University of Montreal

Phone: +01-514-553-6037
Email: lin.zhouhan@gmail.com
Homepage:http://zhouhanlin.webs.com/

**Comment by hantek** [comment]
Hi, I created a PR at #227 to fix this issue.
