### ISSUE TITLE
Clarify the distinction between IterableDataset and IndexableDataset

### ISSUE THREAD

**Issue by o1lo01ol1o** [mila-udem/fuel#219]
Example:

```python
import numpy as np
import theano
from blocks.bricks import Rectifier, Softmax
from blocks.bricks import MLP
from blocks.initialization import IsotropicGaussian, Constant
from blocks.model import Model, ComputationGraph
from blocks.bricks.cost import CategoricalCrossEntropy
from fuel.streams import DataStream
from fuel.datasets import IterableDataset
from fuel.schemes import ShuffledScheme
from blocks.main_loop import MainLoop
from blocks.extensions import FinishAfter, ProgressBar, Printing
from blocks.extensions.monitoring import TrainingDataMonitoring
from blocks.algorithms import GradientDescent, Adam


seed = 1234
rng = np.random.RandomState(seed)
features = rng.uniform(size=(1280, 8))
targets = rng.uniform(low=0, high=1, size=(1280, 1)).astype(np.int32)

dataset = IterableDataset(
    iterables={'features': features, 'targets': targets})

data_stream = DataStream(dataset=dataset, iteration_scheme=ShuffledScheme(batch_size=128, examples=dataset.num_examples))



x = theano.tensor.matrix('features', dtype='float64')
y = theano.tensor.matrix('targets', dtype='int32')

mlp = MLP(activations=[Rectifier(), Softmax()], dims=[8, 4, 2], name='mlp',
               weights_init=IsotropicGaussian(0.1),
               biases_init=Constant(0.))

mlp.initialize()
y_hat = mlp.apply(x)
cg = ComputationGraph(y_hat)
cost = CategoricalCrossEntropy().apply(y_hat, y)
model = Model([cost])



loop = MainLoop(data_stream=data_stream,
                algorithm=GradientDescent(step_rule=Adam(),
                                          cost=cost,
                                          parameters=cg.parameters),
                model=model,
                extensions=[
                            TrainingDataMonitoring([cost],
                                                   prefix="train",
                                                   after_epoch=True),
                            FinishAfter(after_n_epochs=5),
                            ProgressBar(),
                            Printing()]
                )
loop.run()
```

Yields:

C:\Python27\lib\site-packages\fuel\iterator.pyc in __next__(self)
     28     def __next__(self):
     29         if self.request_iterator is not None:
---> 30             data = self.data_stream.get_data(next(self.request_iterator))
     31         else:
     32             data = self.data_stream.get_data()

C:\Python27\lib\site-packages\fuel\streams.pyc in get_data(self, request)
    165     def get_data(self, request=None):
    166         """Get data from the dataset."""
--> 167         return self.dataset.get_data(self.data_state, request)
    168 
    169     def get_epoch_iterator(self, **kwargs):

C:\Python27\lib\site-packages\fuel\datasets\base.pyc in get_data(self, state, request)
    302     def get_data(self, state=None, request=None):
    303         if state is None or request is not None:
--> 304             raise ValueError
    305         return next(state)
    306 

ValueError: 

Original exception:
	ValueError

**Comment by vdumoulin** [comment]
I agree that the error message isn't very helpful.

The reason why you're seeing this error is because `IterableDataset` isn't made to be used in conjunction with iteration schemes. You should use `IndexableDataset` instead. More info [here](https://groups.google.com/d/msg/blocks-users/QFn5YPbct2Q/01c8zvW8AQAJ).

Do you mind if I expand the scope of your ticket to include making the distinction between `IterableDataset` and `IndexableDataset` clearer in the documentation?

**Comment by o1lo01ol1o** [comment]
Yes, please do
