### ISSUE TITLE
fuel doesn't change data path after installed

### ISSUE THREAD

**Issue by hantek** [mila-udem/fuel#224]
If the data path is changed in .fuelrc file after fuel is installed, fuel still tries to read data from its previous data path. However the new settings in .fuelrc should override its previous ones. So it seems to be a bug.

**Comment by dwf** [comment]
Is your $FUEL_DATA_PATH environment variable set? As specified [here](https://fuel.readthedocs.org/en/latest/built_in_datasets.html#environment-variable), the environment variable overrides it.

**Comment by hantek** [comment]
No there is no $FUEL_DATA_PATH in my .bashrc file.

**Comment by dwf** [comment]
That's not what I asked.

Type `echo $FUEL_DATA_PATH`. Is it blank?

**Comment by hantek** [comment]
No it is not. But does fuel writes it somewhere during installation? 'Cause I haven't written it..

**Comment by vdumoulin** [comment]
If you're working in the lab, know that the labwise config files you're sourcing in you bashrc *do* set `FUEL_DATA_PATH`.

To override this, you should explicitly unset this environment variable in your bashrc after you've sourced the lab config files.

**Comment by dwf** [comment]
If this is a LISA machine, it gets written by the lab's global .bashrc that you probably source from within yours.

**Comment by hantek** [comment]
I see. It is set in /Tmp/lisa/os_v4/.local.bashrc
