### ISSUE TITLE
API documentation is almost empty

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [mila-udem/fuel#228]
This is almost the same issue as mila-udem/blocks#832 but Fuel API documentation is absolutely empty except 'Toy dataset' section which is also empty.

**Comment by vdumoulin** [comment]
@hantek in order to build the documentation locally, type

``` bash
sphinx-build -b html docs docs/_build/html
```

inside the repo's root directory. You can then view `docs/_build/html/index.html` in your web browser.

**Comment by hantek** [comment]
#232 is trying to add something for api docs.

**Comment by vdumoulin** [comment]
Closed via #232.
