### ISSUE TITLE
mnist datasets error

### ISSUE THREAD

**Issue by rajendraranabhat** [mila-udem/fuel#248]
Hi,
  I am trying to run this code(using summerschool2015's ipython notebook)

from fuel.datasets import MNIST
train = MNIST( which_sets=('train',), subset=slice(0, 50000))

It give following error,
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-57-76a9bc412e2d> in <module>()
      2 
      3 
----> 4 train = MNIST( which_sets=('train',), subset=slice(0, 50000))
      5 valid = MNIST(which_sets=('train',), subset=slice(50000, 60000))
      6 test = MNIST(which_sets=('test',))

TypeError: __init__() takes exactly 2 arguments (1 given)

I have tried various other way with no luck..Any idea about this error? I have mnist.hdf5 inside fuel_data directory..

**Comment by rajendraranabhat** [comment]
Updated:
  I just restarted the ipython notebook , deleted the fuel-data folder and freshly created from the notebook and it works again :) . Not sure what was the issue!!

**Comment by vdumoulin** [comment]
Glad to see the issue is solved! By the way, you can always ask these sorts of questions on the [mailing list](https://groups.google.com/d/forum/fuel-users). This way you won't have to to open an issue on Github.
