### ISSUE TITLE
Fuel master is broken

### ISSUE THREAD

**Issue by rizar** [mila-udem/fuel#261]
Restarting the tests broke the master branch.

**Comment by dwf** [comment]
I saw this this morning. What exactly is gone wrong?

**Comment by bartvm** [comment]
Just something I noticed: The errors seem to suggest that the current working directory doesn't exist. That would suggest the code changed directory somewhere, but never changed back. A search for `chdir` turns up [this](https://github.com/mila-udem/fuel/blob/master/tests/test_converters.py#L227-L245). My guess is that it crashes somewhere in those lines, leaving Python in the temporary directory that gets deleted later on. From thereon, trying to open any file results in an error.

**Comment by rizar** [comment]
I guess it is the failure in `tests.test_converters.TestAdult.test_convert` that caused the incorrect current directory.

**Comment by rizar** [comment]
Bug also happens locally on my machine. @hantek , if was your pull request, can you please take a look why Adult dataset is broken now?

**Comment by hantek** [comment]
Yes I will check on that

**Comment by hantek** [comment]
I find it out.

In the tests we try to download adult dataset from its original website (https://archive.ics.uci.edu/ml/machine-learning-databases/); but now that site is down. The downloader downloads a message saying something like "Permission denied," but for sure it is not smart enough to find itself tricked... Then the converter tries to convert that error message into a dataset, which ends up with an unexpected error. The test program stucks there, and starts the rest of tests...

**Comment by hantek** [comment]
Is there substitutes for that dataset? Or we change the downloader to download a file into some directory without changing the current working directory (so that one test fails doesn't influence the others)?

**Comment by rizar** [comment]
What about adding a bit of exception handling to make sure that in the
event of failure we end up in the same directory where we started? Also, it
would be great to see a more informative error in such cases, because the
current one did not suggest at all that we could not download...

**Comment by bartvm** [comment]
Maybe something like this in utils: http://stackoverflow.com/a/169112

**Comment by rizar** [comment]
Sounds good to me. @vdumoulin , will you have time in the near future to fix this problem?

**Comment by hantek** [comment]
I will take care of it this night.

**Comment by hantek** [comment]
Hi, I created a PR at #265 to solve the problem. 
The point is to make the test program remain at the right working dir even if any test fails. But the tests on Adult dataset would still fail because the site is offline now.

**Comment by hantek** [comment]
Oh that site is back! It has passed!

**Comment by dwf** [comment]
Should this have been closed?

**Comment by bartvm** [comment]
Yeah. That said, I think a context manager like in #265 would still be good to merge. I believe there are several tests that could make the same thing happen i.e. if one test fails and doesn't change it's working directory back all the subsequent tests fail as well.
