### ISSUE TITLE
SVHN format 1 'bbox_lefts' fields become 65535 after cast from int to uint16

### ISSUE THREAD

**Issue by ablavatski** [mila-udem/fuel#263]
After fuel-convert, SVHN format 1 'bbox_lefts' field become 65535, because previously in 'digitStruct.mat' they were -1.

**Comment by dwf** [comment]
@vdumoulin Mind taking a look at this?

**Comment by ablavatski** [comment]
I already committed the pull request for that bug.
I already committed the pull request for that bug.
