### ISSUE TITLE
Error when install FUEL:ValueError: --enable-jpeg requested but jpeg not found, aborting

### ISSUE THREAD

**Issue by astrung** [mila-udem/fuel#268]
When i install fuel by this command:
 pip install git+git://github.com/mila-udem/fuel.git@stable
I get this error: ValueError: --enable-jpeg requested but jpeg not found, aborting.
I am using Centos 6(OS)-python6.
And when i try to install tables,i get an error:Can not find lhdf5>>I have fixed it by installing HDF5 and adding HDF5_DIR to installed folder.
And then i get this error.How to fix it???
I get this error when process is :"Running setup.py install for pillow"

**Comment by dmitriy-serdyuk** [comment]
Quick googling says, that pillow needs `libjpeg` package. H5py package needs `libhdf5`. Seems, that your package manager didn't install correctly all the dependencies.

**Comment by astrung** [comment]
I have fixed it by install dependencies packages for pillow - install pillow script didn`t setup it > please add check and install dependencies packages for script

**Comment by dmitriy-serdyuk** [comment]
That it is a problem of your package manager or pillow.
