### ISSUE TITLE
How can I construct a Datastream from separate files?

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/fuel#303]
The scenario is that, the train set is composed of duplicated training samples corresponding to different targets.  And the training samples are very large. I want to load the indices in memory and save only one copy of samples in the disk. 
The question is how to construct a data stream from sample indices and load the sample on run?

**Comment by vdumoulin** [comment]
It's probably not very speed efficient, but here's something that comes to my mind: you could construct a dataset composed of indices and targets, and implement a custom `Transformer` object which reads the indices in a batch and replaces them by the actual training samples which are stored elsewhere.

To get you started on how to implement a new transformer, have a look at the [Fuel tutorial](http://fuel.readthedocs.org/en/latest/extending_fuel.html#new-transformers).

**Comment by Beronx86** [comment]
@vdumoulin HI, thanks for your reply. I did as what you said. It works.
