### ISSUE TITLE
Document the implementation of a new DataStream

### ISSUE THREAD

**Issue by arkravitz** [mila-udem/fuel#34]
Could you possibly write some documentation on how to create a new datastream, and which methods to overload? I'm trying but having some trouble knowing what to implement.

**Comment by bartvm** [comment]
Documentation is definitely on the todo-list, but so are many other things... We'll try to get to it ASAP.

Meanwhile, are you trying to write a transformer, or a dataset?

**Comment by arkravitz** [comment]
A dataset (I believe as I'm not really sure what the distinction is). Even just a list of the required methods to override would be amazing.

**Comment by bartvm** [comment]
The only method you *need* to override is `get_data` (as you can tell from the fact that it is an abstract method: https://github.com/bartvm/fuel/blob/master/fuel/datasets/base.py#L133).

If your dataset is state-full e.g. if it uses file handles or iterators internally, then you should also implement `open`. The docstrings of these classes should give you a good idea of what they need to return.

**Comment by arkravitz** [comment]
Awesome, thank you. That's what I assumed, but I didn't want to start using it until I was sure! Thanks again.

**Comment by vdumoulin** [comment]
We've recently overhauled the documentation, and I think it fixes this issue. I'll close, but feel free to re-open if you think we're missing something.
