### ISSUE TITLE
Merging streams

### ISSUE THREAD

**Issue by mishmetall** [mila-udem/fuel#366]
How can I create data stream, that take two streams and produce new one? For example I take image A, concatenate with image B and return 0 if they are similar and 1 if different. 
Or it can be stream that randomly sample few data points, do something with them and return one

**Comment by dmitriy-serdyuk** [comment]
Take a look at [Merge](https://github.com/mila-udem/fuel/blob/3d770b4cc43461f7382e58729eb12c3845dc8287/fuel/transformers/__init__.py#L727) transformer implementation. I basically takes a list of streams, queries them and merges the result into one batch. I your case, the logic of `get_data` method would be different.

Another option using only existing transformers is following. First, you need to merge two streams with `Merge` mentioned above. Second, use `Mapping` transformer with `add_source` argument to produce your labels (if A == B). And finally, filter out images A and B using `FilterSources` transformer.

**Comment by mishmetall** [comment]
Great, thanks! And another question: I see there is ShuffledSceme to iterate over dataset, but I see that it shuffle only ones, not each epoch, is there already implemented feature to shuffle each epoch differently?

**Comment by rizar** [comment]
Sorry for the late reply. In practice every epoch will be shuffled
differently, because every time a new iterator is created.
