### ISSUE TITLE
ILSVRC extremely slow reading using ImageFromBytes

### ISSUE THREAD

**Issue by aam-at** [mila-udem/fuel#370]
Both classes for ImageNet task store encoded images using raw bytes buffer in hdf5 files. Upon reading the data is converted using PIL to numpy array. The conversion takes too long time.

With ImageFromBytes it takes around 11 seconds to read 20 batches of size 256.
Commenting out ToBytes and ImageFromBytes, it takes less than half second.

I tried to use `multiprocessing.Pool` but it didn't help.

```python
from fuel.datasets.imagenet import ILSVRC2012
from fuel.streams import DataStream
from fuel.schemes import ShuffledScheme
from fuel.transformers.defaults import ToBytes
from fuel.transformers.image import ImagesFromBytes


train = ILSVRC2012(('train',))
indices = range(train.num_examples)

stream = DataStream(train, iteration_scheme=ShuffledScheme(indices, 256))
stream = ToBytes(stream, which_sources=('encoded_images',))
stream = ImagesFromBytes(stream, which_sources=('encoded_images',))

epoch = stream.get_epoch_iterator(as_dict=True)
batch_index = 0
import time
s = time.time()
while batch_index < 10:
    batch_index += 1
    batch = next(epoch)
print("took: %f" % (time.time() - s))
```

**Comment by dwf** [comment]
Yeah. There isn't a great solution (that I could find) if you want to store the full images. I've mostly been using the 2010 class as a source for conversion to a pre-cropped H5PYDataset.

**Comment by dwf** [comment]
Here's some code I wrote that helps *a little bit*, insofar as the issue is JPEG decoding being slow. Not much help with speeding up disk I/O. For that I think we'd need to go the Caffe route and write a leveldb backend (which may not be much work for the right person).

```python
from concurrent.futures import ThreadPoolExecutor

import numpy
from jpeg4py import JPEG, JPEGRuntimeError
from PIL import Image
from toolz import flip

class JPEG4PY(SourcewiseTransformer):
    def __init__(self, stream, max_workers=True, **kwargs):
        kwargs.setdefault('produces_examples', stream.produces_examples)
        self.thread_pool = ThreadPoolExecutor(max_workers=max_workers)
        super(JPEG4PY, self).__init__(stream, **kwargs)

    def transform_source_example(self, source, source_name):
        try:
            return JPEG(source).decode().transpose(2, 0, 1)
        except (JPEGRuntimeError, TypeError):
            im = Image.open(io.BytesIO(source.tostring()))
            if im.mode != 'RGB':
                im = im.convert('RGB')
            return numpy.array(im).transpose(2, 0, 1)

    def transform_source_batch(self, source, source_name):
        f = flip(self.transform_source_example, source_name)
        return list(self.thread_pool.map(f, source))
```

**Comment by aam-at** [comment]
Yeah, that quite helps. I am getting 4-5 speed (around 2 seconds) improvement with 8 threads. Do you want to add it to the image transformers?

Btw, there are many transformers which do not have an efficient batch transformation. Shouldn't we fall back on multi-threaded batch transform then? It gives some improvements.

**Comment by dwf** [comment]
jpeg4py calls into C code and releases the GIL, so it is particularly well
suited to parallel decoding. Unfortunately most Python code won't
parallelize like that.

Not sure if we want to add jpeg4py as a hard dependency, either.

**Comment by aam-at** [comment]
For the current implementation, image decoding is a bottleneck, not i/o. That's
why in my opinion leveldb is not necessary yet.

I had a brief look at caffe conversion code for imagenet dataset. And by default
they store decoded data using their native format `Datum` (correct me if I am
wrong). So it is not necessary to jpeg decode it again if encoding is not set.

Maybe option can be added where image will be decoded and stored directly as
numpy array/buffer/string. What issues did you have when trying to store data in
hdf5 using numpy arrays? I think you mentioned about it somewhere.

**Comment by dwf** [comment]
At full resolution a) the files will be huge b) I'm fairly sure that the amount of bytes you will need to read off of disk per minibatch will create an I/O bottleneck. I'd be very surprised if people training with ImageNet on Caffe are not decoding on the fly. The ServerDataStream may help pipeline that.
