### ISSUE TITLE
Document how to write a script that spawns a dataset server before training

### ISSUE THREAD

**Issue by dwf** [mila-udem/fuel#60]
Launching a combo dataset server/experiment script is going to be a pretty common use case. It'd be nice to include some sort of helper to make this as painless as possible.

**Comment by bartvm** [comment]
Right, although I'm not sure whether we should suggest starting the server in a child process, or in an entirely separate process altogether. I've just been running it as an entirely separate process to make sure that I don't end up with strange multiprocessing issues. I just don't know enough about CUDA/HDF5's internals and `multiprocessing` to know whether this could be an issue:
```python
import h5py
import theano

def my_data_stream_constructor(self):
    dataset = H5PYDataset(...)
    data_stream = DataStream(dataset)
    start_server(data_stream)

Process(target=my_data_stream_constructor).start()

# rest of script here

data_stream = ServerDataStream(...)
```
I'm worried that the `fork` command used after importing `h5py` could cause some global state to get screwed up? Users might also be inclined to move `Process.start` to later down the file, but calling `fork` after Theano has allocated memory for everything can be a bad idea as well I think (e.g. https://github.com/Theano/Theano/issues/2184)

The alternative is just to ask the user to do what I did and write two files:
```python
# server.py
dataset = H5PYDataset(...)
data_stream = DataStream(dataset)
start_server(data_stream)
```
```python
# train.py
data_stream = ServerDataStream(...)
```
and do something like `python server.py &; python train.py`
