### ISSUE TITLE
Add 'Adult' dataset to built-in datasets

### ISSUE THREAD

**Issue by vdumoulin** [mila-udem/fuel#88]
You can find info about the Adult dataset [here](http://archive.ics.uci.edu/ml/datasets/Adult).

See these two tutorials (in order) for a crash-course on how to implement a new built-in dataset in Fuel:

* [How to use H5PYDataset to load data in Fuel](http://fuel.readthedocs.org/en/latest/h5py_dataset.html)
* [How to implement a built-in dataset in Fuel](http://fuel.readthedocs.org/en/latest/new_dataset.html)

**Comment by hantek** [comment]
Hi 
I created a PR for this issue, though it hasn't pass Travis right now. I'll go back and check.

**Comment by vdumoulin** [comment]
Closed via #220.
