### ISSUE TITLE
Add Iris dataset to built-in datasets

### ISSUE THREAD

**Issue by vdumoulin** [mila-udem/fuel#89]
You can find info about the Iris dataset [here](https://archive.ics.uci.edu/ml/datasets/Iris).

See these two tutorials (in order) for a crash-course on how to implement a new built-in dataset in Fuel:

* [How to use H5PYDataset to load data in Fuel](http://fuel.readthedocs.org/en/latest/h5py_dataset.html)
* [How to implement a built-in dataset in Fuel](http://fuel.readthedocs.org/en/latest/new_dataset.html)

**Comment by dwf** [comment]
As... an HDF5 file? That's like bringing a bazooka to a knife fight. :P

**Comment by vdumoulin** [comment]
Well... the same remark applies for MNIST and binarized MNIST, no? We would be loading the data in memory by default, so I don't think we would be seeing any significant performance drop.

The reason for storing this as an HDF5 file is mostly so that we keep built-in datasets under a common interface as much as possible.

**Comment by vdumoulin** [comment]
Closed #89 via #185.
